### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by micheleberrettis1** [Moyster/android_local_manifest#2]
Getting this error when starting build:

Starting build with ninja
ninja: Entering directory `.'
ninja: error: 'vendor/moyster/keys/releasekey.pk8', needed by '/home/mib/kernel/out/target/product/m2note/obj/APPS/BasicDreams_intermediates/package.apk', missing and no known rule to make it
build/core/ninja.mk:151: set di istruzioni per l'obiettivo "ninja_wrapper" non riuscito
make: *** [ninja_wrapper] Errore 1

**Comment by m3shat** [comment]
Your pk8 file is corrupted. Check that the file format is correct and it's not an empty or broken file! Had the same error

**Comment by micheleberrettis1** [comment]
You can make your own keys
